### ISSUE TITLE
Latest build errors

### ISSUE THREAD

**Issue by uhlhosting** [ousamabenyounes/docker-yellowlabtools#23]
```
gyp
 ERR! find Python 
gyp 
ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR!
 find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp 
ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python
 **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack
     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 4.18.0-193.28.1.el8_2.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /usr/src/ylt/node_modules/ttf2woff2
gyp ERR! node -v v14.16.0
gyp
 ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> core-js@2.6.12 postinstall /usr/src/ylt/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@5.0.0 postinstall /usr/src/ylt/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/src/ylt/node_modules/node-sass/vendor/linux_musl-x64-83/binding.node
Testing binary
Binary is fine

> jpegoptim-bin@5.1.0 postinstall /usr/src/ylt/node_modules/jpegoptim-bin
> node lib/install.js

  ⚠ spawn /usr/src/ylt/node_modules/jpegoptim-bin/vendor/jpegoptim ENOENT
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c make install
make: gcc: Operation not permitted
make: *** [<builtin>: jpegoptim.o] Error 127

gcc  -g -O2  -DHAVE_CONFIG_H   -c -o jpegoptim.o jpegoptim.c

    at /usr/src/ylt/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm WARN grunt-express@1.4.1 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-inline-angular-templates@0.1.5 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpegoptim-bin@5.1.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpegoptim-bin@5.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T13_03_30_506Z-debug.log
The command '/bin/sh -c git clone https://github.com/gmetais/YellowLabTools.git -b ${VERSION} .   && git checkout e9ab1fd   && chmod -R 777 . && NODE_ENV=development && npm install --only=prod' returned a non-zero code: 1
```

**Comment by gmetais** [comment]
The Python error can be ignored, the ttf2woff2 library tries to compile some Python code, then switches to a fallback in pure NodeJS. We can skip installing Python so that the docker image stays light.

The jpegoptim library tries to find a pre-compiled version, which doesn't seem to exist for Alpine. So it fallbacks to a C++ compilation of the library. And this is failing. The impact on Yellow Lab Tools is that the image compression audit fails to execute.

**Comment by ousamabenyounes** [comment]
i was doing some optimization with my friend @painchaudAlexandre but got some bugs.
I reverted it and i'll do local test instead now sorry for this build error

**Comment by ousamabenyounes** [comment]
build fixed by last @gmetais updates :)
